<?php
/**
 * Adds the Global Climate Strike banner and blackout.
 */

/**
 * Implements hook_menu().
 */
function globalclimatestrike_menu() {
  $items['admin/config/climatestrike'] = array(
    'title' => 'Climate Strike settings',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('globalclimatestrike_settings_form'),
    'access arguments' => array('administer globalclimatestrike'),
    'type' => MENU_CALLBACK,
    //'file' => 'globalclimatestrike.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function globalclimatestrike_permission() {
  return array(
    'administer globalclimatestrike' =>  array(
      'title' => t('Adjust Climate Strike settings'),
      'description' => t('Configure settings for the Climate Strike module'),
    ),
  );
}

/**
 * Settings form.
 */
function globalclimatestrike_settings_form(&$form, &$form_state) {
  $config = config('globalclimatestrike.settings');
  $form = array('#config' => 'globalclimatestrike.settings');

  /**
   * For the full page widget, shows a close button "x" and hides the message about the site being
   * available tomorrow. Defaults to false.
   */
  $form['help'] = array(
    '#type' => 'markup',
    '#markup' => '<p><strong>' . t('This module now does nothing. We recommend uninstalling it.') . '</strong></p><p>' . t('The domain digitalclimatestrike.net was taken over by spammers. The JavaScript previously hosted at that domain is no longer being added to this by by this module.') . '</p><p>' . t('Stay safe out there.') . '</p>',
  );

  return system_settings_form($form);
}

/**
 * Implements hook_config_info().
 */
function globalclimatestrike_config_info() {
  $prefixes['globalclimatestrike.settings'] = array(
    'label' => t('Global Climate Strike'),
    'group' => t('Configuration'),
  );
}

